{% set name = "linkedin-api" %}
{% set version = "2.3.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/linkedin_api-{{ version }}.tar.gz
  sha256: 07ab020440a049e48e6c55d6b61fbab049480225ec8a82f14e5c077ae7ecc984

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - requests
    - beautifulsoup4
    - lxml

test:
  imports:
    - linkedin_api
    - linkedin_api.utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tomquirk/linkedin-api
  summary: Python wrapper for the Linkedin API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
