{% set name = "linkedin-api" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/linkedin_api-{{ version }}.tar.gz
  sha256: a7be3dc950820b08b1eee0cf3517ce36cd47cb61836e1fb8c40115854acf84b5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests
    - beautifulsoup4
    - lxml

test:
  imports:
    - linkedin_api
    - linkedin_api.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tomquirk/linkedin-api
  summary: Python wrapper for the Linkedin API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
