{% set name = "linkedin-api" %}
{% set version = "2.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/linkedin_api-{{ version }}.tar.gz
  sha256: 0a19248a37eaf1cd29d207105e884c73d50f20cfee9d7817d76c552c884f124d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests
    - beautifulsoup4
    - lxml

test:
  imports:
    - linkedin_api
    - linkedin_api.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tomquirk/linkedin-api
  summary: Python wrapper for the Linkedin API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
