{% set name = "linkedin-api" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/linkedin_api-{{ version }}.tar.gz
  sha256: dc0b77ece188b3e7dcbd90da42b6b79d7250020021855e7a592bda496354c797

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests
    - beautifulsoup4
    - lxml

test:
  imports:
    - linkedin_api
    - linkedin_api.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tomquirk/linkedin-api
  summary: Python wrapper for the Linkedin API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
